llama_models_and_saes = {
    "meta-llama/Meta-Llama-3.1-8B-Instruct": {
        "model_id": "meta-llama/Llama-3.1-8B-Instruct",
        "d_model": 4096,
        "expansion_factor": 16,
        "sae_id": "Goodfire/Llama-3.1-8B-Instruct-SAE-l19",
        "sae_filepath": "Llama-3.1-8B-Instruct-SAE-l19.pth",
        "steering_layer": 12,
        "feature_layer": 19,
        "labels_filename": "llama-8b-goodfire-l19.csv",
        "batch_size": 20,
        "threshold_prior_mean": 5,
        "threshold_prior_std": 5,
        "threshold_upper_bound": 100,
        "tensor_parallel_size": 1,
        "quantization" : None,
    },
    "meta-llama/Meta-Llama-3.3-70B-Instruct": {
        "model_id": "meta-llama/Llama-3.3-70B-Instruct",
        "d_model": 8192,
        "expansion_factor": 8,
        "sae_id": "Goodfire/Llama-3.3-70B-Instruct-SAE-l50",
        "sae_filepath": "Llama-3.3-70B-Instruct-SAE-l50.pt",
        "steering_layer": 33,
        "feature_layer": 50,
        "labels_filename": "llama-70b-goodfire-l50.csv",
        "batch_size": 5,
        "threshold_prior_mean": 5,
        "threshold_prior_std": 5,
        "threshold_upper_bound": 100,
        "tensor_parallel_size": 2,
        "quantization" : "fp8",
    },
}